// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnbgkjfzynbrnoeacjwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuYmdramZ6eW5icm5vZWFjand1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTczMzUsImV4cCI6MjA2NTA3MzMzNX0.7OvTCH6-kMVDGaJA_NINaKkylfS9VNdbuiC-e9LHSLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);